#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.xamarin.example.actionbar.tabs.Resource", IsApplication=true)]

namespace com.xamarin.example.actionbar.tabs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_my_schedule = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_sessions = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_speakers = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_whats_on = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_appLauncher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_cartBlue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_certificateBlue = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_dollarBlue = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_giftCard = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_my_schedule = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_sessions = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_tab_speakers = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_tab_whats_on = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_userInfo1 = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int AddressLine1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int AddressLine2 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int AddressLine3 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Description = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int Email = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int ListView = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int Name = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int SignOut = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int frameLayout1 = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int txtAddress = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int txtEmail = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int empty_fragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItemRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int simple_fragment = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int account_tab_label = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int card_tab_label = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int certificates_tab_label = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int deals_tab_label = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int giftCard_tab_label = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int sessions_tab_label = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int signOut = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
